### PR TITLE
CapabilityStatements and Compositions for eOverdracht phase one

### PR DESCRIPTION
**Pull request by furoreSebastiaan**
Please review

### CODE REVIEW

**Comment by furoreSebastiaan** [comment]
@ArdonToonstra  Please next time go to https://github.com/Nictiz/Nictiz-STU3-Zib2017/pull/25/files and add comments at the site where you find the errors. now I have to search the error too and this takes a long time. 

- Improve description and purpose of eOverdrachtOverdrachtsberichtVolwassenen-phase-one profile a bit, including dots. Especially the purpose can be written a bit better, it is now a combination of English an Dutch

I believe the first author (you ;) )  did this correctly. We're speaking of titles like aanmeldbericht or Overdrachtsbericht volwassenen. If we're going to translate this, we're not consistent anymore. I will add a dot at the end of one line for proper grammar. 

- Still missings codes, correct?

Yes, will add them in a new pull request if this one is pulled.

- Include PractitionerRole reference
 In what file?

- Title: perhaps remove 'e-Overdracht'? It now repeats.
Disagree. e-Overdracht is the project title, Overdrachtberich Volwassenen profile title. Copied it of the Aanmeldbericht Author (you).

- Section slicing is now on Title, didn't Aisha provides codes? Please use codes where possible. 

Codes were provided long after this pull request was made.  Will add them in a new pull request.

- Not all mappings have a comment with the concept name in it.
Found it. Fixed it. Error already existed in 

- Payer is a section to deep (and also has no title fixed value) 

Was a style choice, but changed it because of our discussion: Our compositions need not to be human readable.

- Missing RelatedPerson entry and possibly Patient reference here at the 'Persoonsgegevens'

Disagree. Patient reference should always be included in the bundle when using a composition (and it's also in Composition.subject


- Why does the section sendingOrganization has an nested sendingPractitioner section?

Style choice. For human-readability. but will change it because of our discussion: Our compositions need not to be human readable.

- Similar question for recievingPractitioner

Style choice. For human-readability. but will change it because of our discussion: Our compositions need not to be human readable.

**Comment by ArdonToonstra** [comment]
Discussed offline. Awaiting improved pull request.

**Comment by furoreSebastiaan** [comment]
Flattened profiles. Please review @ArdonToonstra or @pieter-edelman-nictiz

**Comment by pieter-edelman-nictiz** [comment]
It looks good to me 👍

**Pull request merged**
