### PR TITLE
zib-DevelopmentChild

### PR DESCRIPTION
**Pull request by furoreSebastiaan**
Please review

### CODE REVIEW

**Comment by ArdonToonstra** [comment]
Please change valueset bindings to reference instead of uri.

**Comment by furoreSebastiaan** [comment]
- [ ] Please change valueset bindings to reference instead of uri.

- [ ] add all possible display values in example - if code is missing = MISSING

**Comment by furoreSebastiaan** [comment]
Please review

**Comment by ArdonToonstra** [comment]
* please add display values in example

**Comment by furoreSebastiaan** [comment]
Changed things for real this time, please review and merge

**Pull request merged**
