### PR TITLE
added profiles and extensions for bladderfunction

### PR DESCRIPTION
**Pull request by furoreSebastiaan**

### CODE REVIEW

**Comment by ArdonToonstra** [comment]
- extension profile has an incorrect url: http://example.org/fhir/StructureDefinition/extension-productType-UrineCatheter
-- is this zib naming and the canonical url our convention?
- extension description -- does the description describe the extension?
- extension please use FHIR resource as targetprofile. Fill in the constrain to our specific targetprofile in the profile itself

- profile itself is missing title
- missing description an purpose
- missing alias fields
- missing short fields
- missing mapping comments

- please provide better meta data about the profile in all related and derived profiles such as descriptions, purpose, contact info, coppy right ect.
- missing mapping declaration in  http://nictiz.nl/fhir/StructureDefinition/zib-bladderfunction-urinecatheter and http://nictiz.nl/fhir/StructureDefinition/zib-bladderfunction-urinecatheterproduct

**Comment by ArdonToonstra** [comment]
@furoreSebastiaan don't forget this one ;)

**Comment by furoreSebastiaan** [comment]
I've corrected the profiles, but a few feedback pointers I do not understand. Please discuss IRL.

**Comment by furoreSebastiaan** [comment]
Closing pull-request, because duplicate.

**Pull request closed without merging**
