### PR TITLE
zib-StrongKidsScore

### PR DESCRIPTION
**Pull request by furoreSebastiaan**
please review

### CODE REVIEW

**Comment by ArdonToonstra** [comment]
- In instances, please always fill in the display value (mandatory within MedMij, for example, https://informatiestandaarden.nictiz.nl/wiki/MedMij:Vdraft_FHIR_IG#Use_of_the_reference_datatype) for now this is probably not done because of missing codes.
- remove fixed value {score} in .valueQuantity.code en reomved fixed values for UCUM -- no requirements to do this through UCUM
- .code slincing is incorrectly rendered in Forge
- all our valueset bindings here are a ResourceReference: please check the box in Forge. Read in the spec about the difference
- How / why do you get StrongKidsScore::ConditionScore ? This is used in the mapping comment. Please adjust to concept name.

**Comment by furoreSebastiaan** [comment]
processed the feedback, please review.

**Comment by furoreSebastiaan** [comment]
processed feedback, please re-review

**Comment by ArdonToonstra** [comment]
@furoreSebastiaan, reviewed and will merge the pull request.

1. Please note somewhere that the terminology codes are still missing!
2. Have a quick look on my two commits.

**Pull request merged**
