### PR TITLE
zib-Bowelfunction, zib-BladderFunction

### PR DESCRIPTION
**Pull request by furoreSebastiaan**
Not sure about the derived zib-MedicalDevice profiles, please check carefully.

### CODE REVIEW

**Comment by furoreSebastiaan** [comment]
fixed issues. Changed mkpaping according to the guidelines and amended the mapping Excel. It should be more clear why there's Zib-BladderFunction-Stoma now.

**Comment by ArdonToonstra** [comment]
* Please create an extension with a reference to the Stoma observation as .related.target is not really fitting because there is not a suitable code for .related.type and the two observations are not necessarily really a group of observations that are performed at the same time.

**Comment by furoreSebastiaan** [comment]
@ArdonToonstra Please check and merge if possible

**Comment by ArdonToonstra** [comment]
- staat een mapping in Zib BladderFunction UrineCatheter Product maar zonder mapping declaratie bovenaan.

**Comment by furoreSebastiaan** [comment]
Could you try a review again?

**Comment by niekfirely** [comment]
Reviewed your actions on Ardon's comments: 
- Zib BladderFunction UrineCatheter Product misses .description/purpose --> **.description is approved, .purpose sentence should be 'Reource necessary to the capture the usage of an urine catheter of a certain type.'**
- mappings in the profile, not per see in the extension + mapping declaration in extension was incomplete --> **approved**
- provide details of extension concept or the zib concept in the profile as well (not only in the extension) --> **approved**
- remove .related profiling --> **approved**
- in Zib BladderFunction UrineCatheter the description and purpose is the same... Please fill this out with a bit of care -- it is also used for rendering purposes --> **.capture sentence should be 'Capture the usage of a urine catheter.'**
- Zib BladderFunction UrineCatheter Product fill in a short description --> **approved**
-- this is applicable for all small derived profiles
- provide custom sliceName for BowelFucntion.code.coding --> **approved**
- staat een mapping in Zib BladderFunction UrineCatheter Product maar zonder mapping declaratie bovenaan. --> **approved**

In addition:
- Verify mappings in all profiles
- Filename Zib BladderFunction UrineCathether is now lowercase, change to CamelCase in line with other filenames
- Zib BladderFunction IncontincenceMaterial: .title value contains version, change to HCIM BladderFunction IncontincenceMaterial
- Zib BladderFunction IncontincenceMaterial: clarify .purpose
- Zib BowelFunction: missing version

**Pull request merged**
